repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8
    
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
    -   id: mypy
    
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
    
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.3
    hooks:
    -   id: pylint
        args:
        - --max-line-length=110
        - --ignore-imports=yes
        - --disable=C0114,E0401
        - --good-names=a,b,i,r,x,y,ATR
